### ISSUE TITLE
Could you help me with Facepunch Steamworks?

### ISSUE THREAD

**Issue by pufoon** [FrostBird347/Fletching-Additions#9]
Hey I'm really sorry to post this here but I didn't know any other way to get in touch.

I noticed you mentioned that you had managed to fix Steam achievements for BABBDI on mac here: https://github.com/Facepunch/Facepunch.Steamworks/issues/591#issuecomment-1636031557

I'm trying to do something similar but I can't for the life of me figure out how to use the fix that barrykooij made. Could you please go into more detail on how to actually use the file that barry posted. 

Thank you, and once again sorry for the off topic post.

**Comment by FrostBird347** [comment]
Hi, I apologise for not being able to provide remotely detailed or useful
information right now. Currently I do not have access to a mac and thus can
not check the exact steps required.
The gist however (from memory) is that you need to look within the
application (right click on the game, within the steamapps folder, and
click on an option labled something along the lines of "show package
contents"), find which files also happen to be in that zip and replace the
matching game's files with those.
I apologise for not being able to provide more detailed/useful help at the
moment and wish you luck with your endeavours.

**Comment by FrostBird347** [comment]
Ok I have now looked into it properly.
Inside the zip file there's a folder called "redistributable_bin", which contains another folder called "osx".
That folder contains the mac frameworks you need to search for within the app.
While the frameworks could be stored literally anywhere in your app, I would recommend searching through the "Frameworks" folder (and all subfolders of that), and then the "Resources" folder.
For example, in BABBDI, those frameworks are stored within `BABBDI_Mac_1.2.5.app/⁨Contents/⁨Frameworks/MonoEmbedRuntime/⁨osx⁩`.
